<center>
    <img src="https://gitlab.com/ibm/skills-network/courses/placeholder101/-/raw/master/labs/module%201/images/IDSNlogo.png"  width="300" alt="cognitiveclass.ai logo"  />
</center>

<h1 align=center><font size = 5>Assignment: SQL Notebook for Peer Assignment</font></h1>

Estimated time needed: **60** minutes.

## Introduction

Using this Python notebook you will:

1.  Understand the Spacex DataSet
2.  Load the dataset  into the corresponding table in a Db2 database
3.  Execute SQL queries to answer assignment questions

## Overview of the DataSet

SpaceX has gained worldwide attention for a series of historic milestones.

It is the only private company ever to return a spacecraft from low-earth orbit, which it first accomplished in December 2010.
SpaceX advertises Falcon 9 rocket launches on its website with a cost of 62 million dollars wheras other providers cost upward of 165 million dollars each, much of the savings is because Space X can reuse the first stage.

Therefore if we can determine if the first stage will land, we can determine the cost of a launch.

This information can be used if an alternate company wants to bid against SpaceX for a rocket launch.

This dataset includes a record for each payload carried during a SpaceX mission into outer space.

### Download the datasets

This assignment requires you to load the spacex dataset.

In many cases the dataset to be analyzed is available as a .CSV (comma separated values) file, perhaps on the internet. Click on the link below to download and save the dataset (.CSV file):

<a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/data/Spacex.csv?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01" target="_blank">Spacex DataSet</a>

### Store the dataset in database table

**it is highly recommended to manually load the table using the database console LOAD tool in DB2**.

<img src = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload.png">

Now open the Db2 console, open the LOAD tool, Select / Drag the .CSV file for the  dataset, Next create a New Table, and then follow the steps on-screen instructions to load the data. Name the new table as follows:

**SPACEXDATASET**

**Follow these steps while using old DB2 UI which is having Open Console Screen**

**Note:While loading Spacex dataset, ensure that detect datatypes is disabled. Later click on the pencil icon(edit option).**

1.  Change the Date Format by manually typing DD-MM-YYYY and timestamp format as DD-MM-YYYY HH\:MM:SS

2.  Change the PAYLOAD_MASS\_\_KG\_  datatype  to INTEGER.

<img src = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload2.png">

**Changes to be considered when having DB2 instance with the new UI having Go to UI screen**

*   Refer to this insruction in this <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sign%20up%20for%20IBM%20Cloud%20-%20Create%20Db2%20service%20instance%20-%20Get%20started%20with%20the%20Db2%20console/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01">link</a> for viewing  the new  Go to UI screen.

*   Later click on **Data link(below SQL)**  in the Go to UI screen  and click on **Load Data** tab.

*   Later browse for the downloaded spacex file.

<img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/browsefile.png" width="800"/>

*   Once done select the schema andload the file.

 <img src="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/spacexload3.png" width="800"/>

In [4]:
!pip install sqlalchemy==1.3.9
!pip install ibm_db_sa

/opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: sqlalchemy==1.3.9 in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (1.3.9)
/opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: ibm_db_sa in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (0.3.5)
Requirement already satisfied: sqlalchemy>=0.7.3 in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ibm_db_sa) (1.3.9)
Requirement already satisfied: ibm-db>=2.0.0 in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ibm_db_sa) (3.0.2)

### Connect to the database

Let us first load the SQL extension and establish a connection with the database

In [8]:
pip install ipython-sql

/opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages/secretstorage/dhcrypto.py:16: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages/secretstorage/util.py:25: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Collecting ipython-sql
  Downloading ipython_sql-0.4.0-py3-none-any.whl (19 kB)
Requirement already satisfied: ipython-genutils>=0.1.0 in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython-sql) (0.2.0)
Requirement already satisfied: sqlalchemy>=0.6.7 in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython-sql) (1.3.9)
Requirement already satisfied: six in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython-sql) (1.15.0)
Requirement already satisfied: ipython>=1.0 in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython-sql) (7.15.0)
Collecting prettytable<1
  Downloading prettytable-0.7.2.tar.bz2 (21 kB)
Collecting sqlparse
  Downloading sqlparse-0.4.1-py3-none-any.whl (42 kB)
     |████████████████████████████████| 42 kB 2.1 MB/s  eta 0:00:01
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (3.0.5)
Requirement already satisfied: jedi>=0.10 in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.17.1)
Requirement already satisfied: decorator in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.4.2)
Requirement already satisfied: pygments in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (2.6.1)
Requirement already satisfied: traitlets>=4.2 in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.3.3)
Requirement already satisfied: pexpect; sys_platform != "win32" in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (4.8.0)
Requirement already satisfied: pickleshare in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.7.5)
Requirement already satisfied: setuptools>=18.5 in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (47.3.1.post20200622)
Requirement already satisfied: backcall in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from ipython>=1.0->ipython-sql) (0.2.0)
Requirement already satisfied: wcwidth in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython>=1.0->ipython-sql) (0.2.4)
Requirement already satisfied: parso<0.8.0,>=0.7.0 in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from jedi>=0.10->ipython>=1.0->ipython-sql) (0.7.0)
Requirement already satisfied: ptyprocess>=0.5 in /opt/conda/envs/Python-3.7-OpenCE/lib/python3.7/site-packages (from pexpect; sys_platform != "win32"->ipython>=1.0->ipython-sql) (0.6.0)
Building wheels for collected packages: prettytable
  Building wheel for prettytable (setup.py) ... done
  Created wheel for prettytable: filename=prettytable-0.7.2-py3-none-any.whl size=13700 sha256=bce19490dd4201f4f8a824aa6e6e10b1ce7740cb20dda9033d7178c7f52ee778
  Stored in directory: /tmp/wsuser/.cache/pip/wheels/8c/76/0b/eb9eb3da7e2335e3577e3f96a0ae9f74f206e26457bd1a2bc8
Successfully built prettytable
Installing collected packages: prettytable, sqlparse, ipython-sql
Successfully installed ipython-sql-0.4.0 prettytable-0.7.2 sqlparse-0.4.1
Note: you may need to restart the kernel to use updated packages.

In [1]:
%load_ext sql

**DB2 magic in case of old UI service credentials.**

In the next cell enter your db2 connection string. Recall you created Service Credentials for your Db2 instance before. From the **uri** field of your Db2 service credentials copy everything after db2:// (except the double quote at the end) and paste it in the cell below after ibm_db_sa://

<img src ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/FinalModule_edX/images/URI.jpg">

in the following format

**%sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name**

**DB2 magic in case of new UI service credentials.**

<img src ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBM-DS0321EN-SkillsNetwork/labs/module_2/images/servicecredentials.png" width=600>  

*   Use the following format.

*   Add security=SSL at the end

**%sql ibm_db_sa://my-username:my-password@my-hostname:my-port/my-db-name?security=SSL**

In [2]:
%sql ibm_db_sa://zkn38047:xgpb%5Ex55xr5gkr7f@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB

## Tasks

Now write and execute SQL queries to solve the assignment tasks.

### Task 1

##### Display the names of the unique launch sites  in the space mission

In [19]:
%%sql

SELECT DISTINCT LAUNCH_SITE FROM SPACEXDATASET

 * ibm_db_sa://zkn38047:***@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB
Done.

[('CCAFS LC-40                                       ',),
 ('CCAFS SLC-40                                      ',),
 ('CCAFSSLC-40                                       ',),
 ('KSC LC-39A                                        ',),
 ('VAFB SLC-4E                                       ',)]

### Task 2

##### Display 5 records where launch sites begin with the string 'CCA'

In [20]:
%%sql
SELECT * FROM SPACEXDATASET LIMIT 5

 * ibm_db_sa://zkn38047:***@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB
Done.

[(datetime.date(2010, 6, 4), datetime.time(18, 45), 'F9 v1.0  B0003                                                                                      ', 'CCAFS LC-40                                       ', 'Dragon Spacecraft Qualification Unit                                                                ', 0, 'LEO                                               ', 'SpaceX                                                                                              ', 'Success                                                                                             ', 'Failure (parachute)                                                                                 '),
 (datetime.date(2010, 12, 8), datetime.time(15, 43), 'F9 v1.0  B0004                                                                                      ', 'CCAFS LC-40                                       ', 'Dragon demo flight C1, two CubeSats, barrel of Brouere cheese                                       ', 0, 'LEO (ISS)                                         ', 'NASA (COTS) NRO                                                                                     ', 'Success                                                                                             ', 'Failure (parachute)                                                                                 '),
 (datetime.date(2012, 5, 22), datetime.time(7, 44), 'F9 v1.0  B0005                                                                                      ', 'CCAFS LC-40                                       ', 'Dragon demo flight C2                                                                               ', 525, 'LEO (ISS)                                         ', 'NASA (COTS)                                                                                         ', 'Success                                                                                             ', 'No attempt                                                                                          '),
 (datetime.date(2012, 10, 8), datetime.time(0, 35), 'F9 v1.0  B0006                                                                                      ', 'CCAFS LC-40                                       ', 'SpaceX CRS-1                                                                                        ', 500, 'LEO (ISS)                                         ', 'NASA (CRS)                                                                                          ', 'Success                                                                                             ', 'No attempt                                                                                          '),
 (datetime.date(2013, 3, 1), datetime.time(15, 10), 'F9 v1.0  B0007                                                                                      ', 'CCAFS LC-40                                       ', 'SpaceX CRS-2                                                                                        ', 677, 'LEO (ISS)                                         ', 'NASA (CRS)                                                                                          ', 'Success                                                                                             ', 'No attempt                                                                                          ')]

### Task 3

##### Display the total payload mass carried by boosters launched by NASA (CRS)

In [21]:
%%sql
    SELECT SUM(PAYLOAD_MASS__KG_) from spacexdataset where customer = 'NASA (CRS)'

 * ibm_db_sa://zkn38047:***@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB
Done.

[(45596,)]

### Task 4

##### Display average payload mass carried by booster version F9 v1.1

In [22]:
%%sql
    select AVG(payload_mass__kg_) from spacexdataset where booster_version = 'F9 v1.1'

 * ibm_db_sa://zkn38047:***@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB
Done.

[(Decimal('2928.400000'),)]

### Task 5

##### List the date when the first succesful landing outcome in ground pad was acheived.

*Hint:Use min function*

In [24]:
%%sql

    SELECT MIN(DATE)
        FROM SPACEXDATASET
        WHERE LANDING_OUTCOME = 'Success (ground pad)'

 * ibm_db_sa://zkn38047:***@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB
Done.

[(datetime.date(2015, 12, 22),)]

### Task 6

##### List the names of the boosters which have success in drone ship and have payload mass greater than 4000 but less than 6000

In [25]:
%%sql
    SELECT BOOSTER_VERSION
        FROM SPACEXDATASET
        WHERE LANDING_OUTCOME IN ('Success (drone ship)')
            and payload_mass__kg_ > 4000 and payload_mass__kg_ < 6000

 * ibm_db_sa://zkn38047:***@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB
Done.

[('F9 FT B1022                                                                                         ',),
 ('F9 FT B1026                                                                                         ',),
 ('F9 FT  B1021.2                                                                                      ',),
 ('F9 FT  B1031.2                                                                                      ',)]

### Task 7

##### List the total number of successful and failure mission outcomes

In [26]:
%%sql
    SELECT COUNT(*)
        FROM SPACEXDATASET
        WHERE mission_outcome in ('Success','Failure')

 * ibm_db_sa://zkn38047:***@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB
Done.

[(Decimal('99'),)]

### Task 8

##### List the   names of the booster_versions which have carried the maximum payload mass. Use a subquery

In [27]:
%%sql
    SELECT DISTINCT BOOSTER_VERSION
        FROM SPACEXDATASET S
        WHERE EXISTS (SELECT MAX(PAYLOAD_MASS__KG_) FROM SPACEXDATASET X WHERE S.BOOSTER_VERSION = X.BOOSTER_VERSION GROUP BY X.BOOSTER_VERSION)

 * ibm_db_sa://zkn38047:***@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB
Done.

[('F9 B4  B1039.2                                                                                      ',),
 ('F9 B4  B1040.2                                                                                      ',),
 ('F9 B4  B1041.2                                                                                      ',),
 ('F9 B4  B1043.2                                                                                      ',),
 ('F9 B4 B1039.1                                                                                       ',),
 ('F9 B4 B1040.1                                                                                       ',),
 ('F9 B4 B1041.1                                                                                       ',),
 ('F9 B4 B1042.1                                                                                       ',),
 ('F9 B4 B1043.1                                                                                       ',),
 ('F9 B4 B1044                                                                                         ',),
 ('F9 B4 B1045.1                                                                                       ',),
 ('F9 B4 B1045.2                                                                                       ',),
 ('F9 B5  B1046.1                                                                                      ',),
 ('F9 B5 B1046.2                                                                                       ',),
 ('F9 B5 B1046.3                                                                                       ',),
 ('F9 B5 B1046.4                                                                                       ',),
 ('F9 B5 B1047.2                                                                                       ',),
 ('F9 B5 B1047.3                                                                                       ',),
 ('F9 B5 B1048.2                                                                                       ',),
 ('F9 B5 B1048.3                                                                                       ',),
 ('F9 B5 B1048.4                                                                                       ',),
 ('F9 B5 B1048.5                                                                                       ',),
 ('F9 B5 B1049.2                                                                                       ',),
 ('F9 B5 B1049.3                                                                                       ',),
 ('F9 B5 B1049.4                                                                                       ',),
 ('F9 B5 B1049.5                                                                                       ',),
 ('F9 B5 B1049.6                                                                                       ',),
 ('F9 B5 B1049.7                                                                                       ',),
 ('F9 B5 B1051.2                                                                                       ',),
 ('F9 B5 B1051.3                                                                                       ',),
 ('F9 B5 B1051.4                                                                                       ',),
 ('F9 B5 B1051.5                                                                                       ',),
 ('F9 B5 B1051.6                                                                                       ',),
 ('F9 B5 B1056.2                                                                                       ',),
 ('F9 B5 B1056.3                                                                                       ',),
 ('F9 B5 B1056.4                                                                                       ',),
 ('F9 B5 B1058.2                                                                                       ',),
 ('F9 B5 B1058.3                                                                                       ',),
 ('F9 B5 B1058.4                                                                                       ',),
 ('F9 B5 B1059.2                                                                                       ',),
 ('F9 B5 B1059.3                                                                                       ',),
 ('F9 B5 B1059.4                                                                                       ',),
 ('F9 B5 B1060.2                                                                                       ',),
 ('F9 B5 B1060.3                                                                                       ',),
 ('F9 B5B1047.1                                                                                        ',),
 ('F9 B5B1048.1                                                                                        ',),
 ('F9 B5B1049.1                                                                                        ',),
 ('F9 B5B1050                                                                                          ',),
 ('F9 B5B1051.1                                                                                        ',),
 ('F9 B5B1054                                                                                          ',),
 ('F9 B5B1056.1                                                                                        ',),
 ('F9 B5B1058.1                                                                                        ',),
 ('F9 B5B1059.1                                                                                        ',),
 ('F9 B5B1060.1                                                                                        ',),
 ('F9 B5B1061.1                                                                                        ',),
 ('F9 B5B1062.1                                                                                        ',),
 ('F9 B5B1063.1                                                                                        ',),
 ('F9 FT  B1021.2                                                                                      ',),
 ('F9 FT  B1029.2                                                                                      ',),
 ('F9 FT  B1031.2                                                                                      ',),
 ('F9 FT  B1032.2                                                                                      ',),
 ('F9 FT  B1035.2                                                                                      ',),
 ('F9 FT  B1036.2                                                                                      ',),
 ('F9 FT  B1038.2                                                                                      ',),
 ('F9 FT B1019                                                                                         ',),
 ('F9 FT B1020                                                                                         ',),
 ('F9 FT B1021.1                                                                                       ',),
 ('F9 FT B1022                                                                                         ',),
 ('F9 FT B1023.1                                                                                       ',),
 ('F9 FT B1024                                                                                         ',),
 ('F9 FT B1025.1                                                                                       ',),
 ('F9 FT B1026                                                                                         ',),
 ('F9 FT B1029.1                                                                                       ',),
 ('F9 FT B1030                                                                                         ',),
 ('F9 FT B1031.1                                                                                       ',),
 ('F9 FT B1032.1                                                                                       ',),
 ('F9 FT B1034                                                                                         ',),
 ('F9 FT B1035.1                                                                                       ',),
 ('F9 FT B1036.1                                                                                       ',),
 ('F9 FT B1037                                                                                         ',),
 ('F9 FT B1038.1                                                                                       ',),
 ('F9 v1.0  B0003                                                                                      ',),
 ('F9 v1.0  B0004                                                                                      ',),
 ('F9 v1.0  B0005                                                                                      ',),
 ('F9 v1.0  B0006                                                                                      ',),
 ('F9 v1.0  B0007                                                                                      ',),
 ('F9 v1.1                                                                                             ',),
 ('F9 v1.1  B1003                                                                                      ',),
 ('F9 v1.1 B1010                                                                                       ',),
 ('F9 v1.1 B1011                                                                                       ',),
 ('F9 v1.1 B1012                                                                                       ',),
 ('F9 v1.1 B1013                                                                                       ',),
 ('F9 v1.1 B1014                                                                                       ',),
 ('F9 v1.1 B1015                                                                                       ',),
 ('F9 v1.1 B1016                                                                                       ',),
 ('F9 v1.1 B1017                                                                                       ',),
 ('F9 v1.1 B1018                                                                                       ',)]

### Task 9

##### List the records which will display the month names, failure landing_outcomes in drone ship ,booster versions, launch_site for the months in year 2015

In [32]:
%%sql
    SELECT
        TO_CHAR(DATE,'MON') MONTH_NAME,
        BOOSTER_VERSION,
        LAUNCH_SITE,
        LANDING_OUTCOME
        FROM SPACEXDATASET 
        WHERE YEAR(DATE) = '2015'
            AND LANDING_OUTCOME = 'Failure (drone ship)'

 * ibm_db_sa://zkn38047:***@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB
Done.

[('JAN', 'F9 v1.1 B1012                                                                                       ', 'CCAFS LC-40                                       ', 'Failure (drone ship)                                                                                '),
 ('APR', 'F9 v1.1 B1015                                                                                       ', 'CCAFS LC-40                                       ', 'Failure (drone ship)                                                                                ')]

### Task 10

##### Rank the  count of  successful landing_outcomes between the date 2010-06-04 and 2017-03-20 in descending order.

In [34]:
%%sql
    SELECT
        LANDING_OUTCOME,
        count(*) launch_count
    FROM SPACEXDATASET
    WHERE DATE BETWEEN TO_dATE('2010-06-04','YYYY-MM-DD') AND TO_DATE('2017-03-20','YYYY-MM-DD')
    GROUP BY LANDING_OUTCOME
    ORDER BY launch_count DESC

 * ibm_db_sa://zkn38047:***@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB
Done.

[('No attempt                                                                                          ', Decimal('10')),
 ('Failure (drone ship)                                                                                ', Decimal('5')),
 ('Success (drone ship)                                                                                ', Decimal('5')),
 ('Controlled (ocean)                                                                                  ', Decimal('3')),
 ('Success (ground pad)                                                                                ', Decimal('3')),
 ('Failure (parachute)                                                                                 ', Decimal('2')),
 ('Uncontrolled (ocean)                                                                                ', Decimal('2')),
 ('Precluded (drone ship)                                                                              ', Decimal('1'))]

In [38]:
%%sql
select * from spacexdataset where day(date) = 'Friday'

 * ibm_db_sa://zkn38047:***@dashdb-txn-sbox-yp-dal09-10.services.dal.bluemix.net:50000/BLUDB
Done.

DBAPIError: (ibm_db_dbi.Error) ibm_db_dbi::Error: [IBM][CLI Driver][DB2/LINUXX8664] SQL0420N  Invalid character found in a character string argument of the function "DECFLOAT".  SQLSTATE=22018 SQLCODE=-420
(Background on this error at: http://sqlalche.me/e/dbapi)

### Reference Links

*   <a href ="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20String%20Patterns%20-%20Sorting%20-%20Grouping/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01&origin=www.coursera.org">Hands-on Lab : String Patterns, Sorting and Grouping</a>

*   <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Built-in%20functions%20/Hands-on_Lab__Built-in_Functions.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01&origin=www.coursera.org">Hands-on Lab: Built-in functions</a>

*   <a  href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Labs_Coursera_V5/labs/Lab%20-%20Sub-queries%20and%20Nested%20SELECTs%20/instructional-labs.md.html?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01&origin=www.coursera.org">Hands-on Lab : Sub-queries and Nested SELECT Statements</a>

*   <a href="https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-3-SQLmagic.ipynb?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01">Hands-on Tutorial: Accessing Databases with SQL magic</a>

*   <a href= "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-DB0201EN-SkillsNetwork/labs/Module%205/DB0201EN-Week3-1-4-Analyzing.ipynb?utm_medium=Exinfluencer&utm_source=Exinfluencer&utm_content=000026UJ&utm_term=10006555&utm_id=NA-SkillsNetwork-Channel-SkillsNetworkCoursesIBMDS0321ENSkillsNetwork26802033-2021-01-01">Hands-on Lab: Analyzing a real World Data Set</a>

## Author(s)

<h4> Lakshmi Holla </h4>

## Other Contributors

<h4> Rav Ahuja </h4>

## Change log

| Date | Version | Changed by | Change Description |
|------|--------|--------|---------|
| 2021-07-09 | 0.2 |Lakshmi Holla | Changes made in magic sql|
| 2021-05-20 | 0.1 |Lakshmi Holla | Created Initial Version |

## <h3 align="center"> © IBM Corporation 2021. All rights reserved. <h3/>